language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - 6
  - 7
  - 8
  - 8.9.4 # explicit branch used for deploying docs
branches:
  only:
    - master
    - /^v[0-9]/
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 8.9.4
before_deploy: npm run docs
deploy:
  - provider: pages
    local-dir: docs
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
      node: 8.9.4
  - provider: npm
    email: developer@amadeus.com
    api_key: $NPM_API_KEY
    tag: beta
    on:
      tags: true
