language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - lts/*
  - 5
  - 6
  - 7
  - 8
deploy:
  provider: npm
  email: developer@amadeus.com
  api_key:
    secure: [insert npm api key]
  on:
    tags: true
