language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - lts/*
  - 6
  - 7
  - 8
branches:
  only:
    - master
    - /^v[0-9]/
matrix:
  fast_finish: true
  allow_failures:
  - node_js: lts/*
before_deploy: npm run docs
deploy:
  - provider: pages
    local-dir: docs
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
#   provider: npm
#   email: developer@amadeus.com
#   api_key:
#     secure: [insert npm api key]
#   on:
#     tags: true
