language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - lts/*
  - 6
  - 7
  - 8
branches:
  only:
    - master
    - /^v[0-9]/
matrix:
  fast_finish: true
  allow_failures:
  - node_js: lts/*
# deploy:
#   provider: npm
#   email: developer@amadeus.com
#   api_key:
#     secure: [insert npm api key]
#   on:
#     tags: true
